# Generated by Django 5.0.1 on 2024-02-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년'), (5, '기타')], verbose_name='학년')),
                ('result', models.CharField(choices=[('frontend', '프론트엔드'), ('backend', '백엔드'), ('fullstack', '풀스택'), ('plan/design', '기획/디자인')], max_length=15, verbose_name='결과')),
            ],
        ),
    ]
