# Generated by Django 5.0.1 on 2024-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(choices=[(1, '1학년'), (2, '2학년'), (3, '3학년'), (4, '4학년 이상')], verbose_name='학년'),
        ),
    ]
